version: "3.2"
services:
  api-server:
    image:
      api-server
    restart: unless-stopped
    ports:
      - "5000:5000"

  react-app:
    image:
      react-app
    stdin_open:
      true
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api-server
