version: "3.2"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /app/node_modules
      - /backend:/app
    restart: unless-stopped
    ports:
      - "5000:5000"

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - /frontend:/app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - backend